using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class VRAIController : MonoBehaviour
{
    [SerializeField] VoiceInputter voiceInputer;
    //[SerializeField] WhisperSpeechToText whisperSpeechToText;
    [SerializeField] ChatGPTManager chatGPTManager;
    [SerializeField] VoiceVoxManager voiceVoxManager;
    [SerializeField] VoiceOutputter voiceOutputer;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    /// <summary>
    /// ï¿½}ï¿½Cï¿½Nï¿½Ì‰ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½Í‚ğ•¶ï¿½ï¿½ï¿½Ö•ÏŠï¿½ ï¿½ï¿½ ï¿½Ô“ï¿½ï¿½ì¬ ï¿½ï¿½ ï¿½Ô“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ö•ÏŠï¿½ ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½oï¿½ï¿½
    /// </summary>
    void Talk()
    {
        AudioClip inputAudio = voiceInputer.InputVoice();
        //string inputText = whisperSpeechToText.SpeechToText(inputAudio);
        //string outputText = chatGPTManager.MakeResponse(inputText);
        //AudioClip voiceVox = voiceVoxManager.TextToSpeech(outputText);
        //voiceOutputer.OutputVoice(voiceVox);
    }
}
